# This is the file with main settings; some settings can be commented out
# (mostly in `Advanced`, as others are needed to typeset the document)
# MAIN SETTINGS - Title, Author, etc.
title: |
  Algorithmic Analysis of Medieval\
  Arabic Biographical Collections\
author: |
  Maxim Romanov\
  *University of Vienna*
abstract: |
  \noindent Arabic biographical collections constitute one of the most voluminous and unexplored genres in the Arabic literary tradition. They are particularly valuable as a source for the social history of the Islamic world, especially up until 1500 CE, before which we are often poorly served by documentary evidence. Numbered in the hundreds, biographical collections include hundreds to tens of thousands of biographies and thus are ideal for prosopographical research of any kind. Scholars have recognized the value of these texts for decades, but their sheer volume has posed a formidable challenge, so their potential has remained untapped. This paper offers an efficient method for studying these texts through algorithmic analysis, which is here understood as a step-by-step reduction of texts written in a natural language to machine-readable data, and exploratory techniques that rely heavily on the use of graphs, cartograms and networks to identify and interpret chronological, geographical and social patterns from these texts. While the method so far has been applied only to a small number of our texts, I will also lay out current work in progress aimed at the development of maintainable infrastructure that will facilitate the analysis of not only all surviving texts, but also all of them taken together. The article is published in *Speculum*, Volume 92, Number S1 (October 2017).
date: \today

# GENERAL SETTINGS - Elements that should go into the final output;
draft_folder: ./draft/
draft_in: masterdraft_autogenerated
draft_out: masterdraft_autogenerated
bibliography_master: ./bib/bibliography_master.bib
bibliography: biblio.bib
csl: ./bib/cms-fullnote.csl
latex_template: ./templates/t_default.latex

# Templates: 
# - `t_default.latex`: documentclass: article, comment out toc (#toc: --toc)
# - `t_brill.latex`: documentclass: report, toc: --toc

# ADVANCED SETTINGS - to tweak formatting;

papersize: a4
indent: True
fontsize: 12pt
documentclass: article
#toc: --toc
header-includes: |
  \setmainfont{Baskerville}
  \setmonofont{Lucida Grande}
  \newfontfamily\arabicfont[Script=Arabic]{Amiri}